Update get_urls function to return urlpatterns
Use of patterns is deprecated since django 1.8.  You can use plain lists now.
This would now work for django >1.9 also fix the "ImportError: cannot import name 'patterns'" error.